### ISSUE TITLE
Packages directory

### ISSUE THREAD

**Issue by kerams** [ploeh/Numsense#24]
Has it been submitted by accident or on purpose? The zipped repo is already 45MB, which is not the best.

**Comment by kerams** [comment]
Ok, I've just noticed:

>All additional binaries not part of .NET 4.5 must also be added to the repository, so that it would be possible to pull down the repository and immediately be able to compile and run all tests.

Still, I'd be interested in hearing about the reasoning behind this.

**Comment by ploeh** [comment]
http://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful

**Comment by kerams** [comment]
Interesting, thank you.

**Comment by mexx** [comment]
@ploeh any interest in using [Paket](https://fsprojects.github.io/Paket/). I see the most arguments still apply, but the restore of `Paket` is consistent in contrast to `NuGet`s one.

**Comment by ploeh** [comment]
Which problem (that we have) does Paket solve that NuGet doesn't solve?

**Comment by mexx** [comment]
As we have no problem, it's equal to NuGet.
