### ISSUE TITLE
CLA formatting

### ISSUE THREAD

**Issue by mexx** [ploeh/Numsense#4]
![04-01-2016 11-27-10 - cla formatting](https://cloud.githubusercontent.com/assets/378088/12087833/7b4d5134-b2d6-11e5-8daa-0e541969a6a0.png)

I think `Disclaimer` section should stand on its own, right?

**Comment by ploeh** [comment]
Yes, that sounds correct. Thank you for pointing that out. :+1: 

I'll change it, but that'll mean that if you ever want to submit another contribution, you'll have to approve the changed version...

**Comment by ploeh** [comment]
Done... I hope...

The problem was due to unprintable characters, so I hope I got rid of them all... The gist file editor isn't the greatest for that sort of work...

**Comment by mexx** [comment]
Looks good.

I have no problems with signing it once again. ;)
